baseURL = "https://infosec-startups.github.io/"
languageCode = "en-us"
title = "Indian Infosec Curated Start-up List"

[ params ]
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Product based"
tag = "product"
icon = "app-store"

[[ params.nav ]]
name = "Service based"
tag = "services"
icon = "user-shield"